pub mod backends;
pub mod gui;
pub mod rag;

#[path = "core/app_paths.rs"]
pub mod app_paths;
#[path = "core/config.rs"]
pub mod config;
#[path = "core/history.rs"]
pub mod history;
#[path = "core/i18n.rs"]
pub mod i18n;
#[path = "core/logging.rs"]
pub mod logging;
#[path = "core/prompt_profiles.rs"]
pub mod prompt_profiles;
#[path = "core/theme.rs"]
pub mod theme;
#[path = "core/update.rs"]
pub mod update;
#[path = "core/window_context.rs"]
pub mod window_context;
